# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    jobs:
  my-job:
    permissions:
      contents: read
      pull-requests: write

  publish-npm:
    needs: build
jobs:
  my-job:
    permissions:
      contents: read
      pull-requests: write
